### ISSUE TITLE
Infusion Enchantment crash on startup

### ISSUE THREAD

**Issue by Shahelion** [makeoo/Gadomancy#50] opened 2016-02-13 04:41 UTC
https://gist.github.com/Zsashas/daefb4c4b928d89519c3

**Comment by Shadows-of-Fire** [comment] 2016-02-13 05:49
Attempt without MultiMC. I've seen numerous issues involving it.

**Comment by Shahelion** [comment] 2016-02-13 05:59
It must be the new enchants added with the latest update. What enchantments were added?

**Comment by HellFirePvP** [comment] 2016-02-13 10:37
An enchantment for armor disguise and an enchantment to reveal nodes - the thaumonomicon should provide the necessary information - the issue however seems to be caused by an id conflict. Try finding a free ID for the enchantment "Revealing" and try again. ID configurations can be made in the config file.

**Comment by Shahelion** [comment] 2016-02-13 10:57
If it was an ID conflict, it would say so. I made sure it was a free ID already. Something is wrong with the Infusion recipe for the enchantment, however.

**Comment by HellFirePvP** [comment] 2016-02-13 11:04
Well that's kinda awkward then. So what modpack are you using and what ID did you assign to the enchantment?

**Comment by Shahelion** [comment] 2016-02-14 00:22
Custom pack, and 53.

**Comment by HellFirePvP** [comment] 2016-02-14 03:09
Hmm.. i wonder what might be causing it. To (kind of) clear it up: The enchantment itself doesn't load correctly; so when we try to register the infusion-enchantment recipe to thaumcraft, it tries to get a value of of our enchantment and then it crashes, because the enchantment is kind of non-existent at that point. I don't really know why, but i guess it might be another mod modifying something with enchantments in general... i'll have a look at it - sorry if that won't be in 1-2 days but i got tests coming up in university, so i can't really focus on the mod...

**Comment by Shadows-of-Fire** [comment] 2016-02-14 03:13
Im still fairly certain its an issue with multimc. Does it at all reproduce on the vanilla client?

**Comment by HellFirePvP** [comment] 2016-04-18 20:50
Unable to reproduce - cause: might be an issue with enchantment id's or multimc as suggested by Shadows-of-Fire

CLOSED

**Closed as completed by HellFirePvP** 2016-04-18 20:50 UTC
