### ISSUE TITLE
Crash on first entering the nether

### ISSUE THREAD

**Issue by kayila** [makeoo/Gadomancy#51] opened 2016-02-14 06:00 UTC
So.... I tried to enter the nether today, first player on the server to go in, and I got this error:

`Description: Ticking screen

java.lang.ClassCastException: makeo.gadomancy.common.entities.EntityPermNoClipItem cannot be cast to net.minecraft.entity.EntityLivingBase
    at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
    at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

Full crash report:
https://gist.github.com/kayila/657811077e6156332274

I tried to get the nether to regen, and got the same error... Crashes the client to desktop, while the server doesn't have a problem.

**Comment by Shadows-of-Fire** [comment] 2016-02-14 06:43
Im not super familoar with gadomancy's code, but if you were wearing an ethereal (familiarEntityPermNoClipItem)? Try removing it. Otherwise i have no clue

**Comment by kayila** [comment] 2016-02-14 07:41
Nope... I had a title scroll, steel chest plate, osmium boots, and i think an iron helmet. Very early game, the only thing I even had on my thaumcraft related was a thaumometer and goldbanded greatwood wand with no foci.

**Comment by Shadows-of-Fire** [comment] 2016-02-14 07:42
That class shouldnt just pop up randomly. Idk if they overwrite wisps but try difficulty 0

**Comment by Shadows-of-Fire** [comment] 2016-02-14 07:48
Well looking through the code since im finally off mobile... Since im not super versed in java i can only tell so much, but that EntityPermNoClipItem seems to apply to Aura Pylons in some way. First off, might be an entity ID conflict somewhere. Might just be a better idea to wait for Hellfire or Makeoo to show up.

**Comment by HellFirePvP** [comment] 2016-02-14 11:25
Guessed right, the "EntityPermNoClipItem" is the item when you throw a crystallized essentia into an aura pylon. If there is no pylon, this entity drops as normal EntityItem.

We don't really overwrite any entities or replace anything, but yea.. "That class shouldn't just pop up randomly" is probably a correct statement here...

That might end up being a real problem.. - So i guess what's going wrong is an ID conflict? So that another mod registers an entity - that's actually a "EntityLiving" - onto the same ID as gadomancy's EntityPermNoClipItem - which then leads to the server sending a wrong packet. The thing is, the server doesn't crash because the ID -> Entity mapping is mostly used on client side.

I guess you did install the same mods on server and client side. May i ask what your modpack is, so i'm able to reproduce the issue?

**Comment by kayila** [comment] 2016-02-14 15:43
It's a private pack that I maintain for myself and a few friends. The mod list is shown in the crash report, but if there's a way I can send you a private message I'll send you a link to the launcher that will pull all the files for you.

**Comment by HellFirePvP** [comment] 2016-02-14 15:58
you can send me a private message on curseforge ( http://minecraft.curseforge.com/members/HellFirePvP ) - so yea, i don't really want to download all the mods manually and even then the configs are different..

**Comment by HellFirePvP** [comment] 2016-04-18 20:39
The bug is not caused by Gadomancy. We think it's caused by another mod - closing.

**Closed as completed by HellFirePvP** 2016-04-18 20:39 UTC
Labels: bug, invalid
